<script src="assets/js/snap.svg-min.js"></script>
<script src="assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
<script src="assets/js/vendor/jquery.min.js"></script>
<script src="assets/js/vendor/bootstrap.min.js"></script>
<script src="assets/js/jquery.bxslider.js"></script>
<script src="assets/js/jquery.flexslider.js"></script>
<script src="assets/js/jquery.prettyPhoto.js"></script>
<script src="assets/js/jquery.appear.js"></script>
<script src="assets/js/parallax.js"></script>
<script src="assets/js/isotope.pkgd.js"></script>
<script src="assets/js/owl.carousel.js"></script>
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script src="assets/js/gmap3.min.js"></script>
<script src="assets/js/classie.js"></script>
<script src="assets/js/gnmenu.js"></script>
<script src="assets/js/classie.js"></script>

<script src="assets/js/jquery-validation/jquery.validate.min.js"></script>
<script src="assets/js/jquery.tooltipster.js"></script>
<script src="assets/js/alertify.min.js"></script>
<script src="assets/js/jquery.modal.min.js"></script>
<script src="assets/js/main.js"></script>
<script src="assets/js/jquery.blockUI.js"></script>
<script src="assets/js/unitegallery.min.js"></script>
<script src="assets/js/ug-theme-grid.js"></script>
<script src="assetsjs/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>